### PR TITLE
WIP: CM1 Lifter Optimization

### PR DESCRIPTION
**Pull request by tsupinie**
I've come up with a preliminary optimization to the CM1 lifter. Basically, each lifter has a `static constexpr bool lift_from_lcl` value that says whether it should lift from the LCL on every iteration or not. There's then a `if constexpr` check in `Parcel::lift_parcel()` that checks to see whether `lift_from_lcl` true, and if it's not, updates the starting pressure on each loop iteration.

One other wrinkle is that the lifter functors return the parcel virtual temperature instead of sensible temperature. Because I need the sensible temperature, I had to move the virtual temperature computation to its own function associated with the lifters. That then gets called from `Parcel::lift_parcel()` on every loop iteration.

This all compiles fine, but, it seems like `_solve_cm1()`  has trouble converging with the small pressure step size in the test sounding. If I run the tests as-is, it hangs on the CM1 parcel lifter tests. To get it to finish, I can do one of the following:

* Artificially limit the number of iterations in `_solve_cm1()` (to, say, 50). This gives a wildly wrong answer (CAPE > 2x what it should be).
* Only reset the starting parcel pressure and temperature when the pressure difference gets above a certain value `dp_reset`. That also gives a wildly wrong answer, but the wrongness gets less as `dp_reset` gets bigger, which seems like it will eventually converge to the correct solution when `dp_reset` is the depth of the column. (Which puts us back to where we were before.)

### CODE REVIEW

**Comment by keltonhalbert** [comment]
It had been a while since I looked at the internal workings of the CM1 solver, so I took the opportunity to refresh myself to try and understand what's breaking. Good news is, I think I know what's going on, bad news is, I'm still not sure how to solve the problem at hand. 

Some background that is necessary... 

The CM1 parcel lifter can be broken up into 3 chunks:
- The functor/wrapper that gets called in the outer lifting-loop
- The forward-solver that integrates from the LCL to the desired level in dp increments
- The iterative-solver that converges to the correct value at the desired level for every dp

In pseudo-code, putting all the function calls together looks something like:
```
lcl_pres, lcl_t = calc_lcl(...);
for k in range(hght_levs[idx_lcl], hght_levs.length-1):
    ...
    new_pcl_pres = pres[k+1]
    new_pcl_t, next_lev_t;
    for pres_small_step in range(lcl_pres, new_pcl_pres, dp):
        ...
        t_solve;
        for iter in range(n_iter_solve):
            ...
            if (converge) t_solve = final_iter_t;
        next_lev_t = t_solve;
    // the return value is the last integrated level
    new_pcl_t = next_lev_t;
    return new_pcl_t;  
```

So, now onto the problem. The adiabatic lifter has to keep track of state in order to handle the vapor, ice and liquid mixing ratio budgets, where the pseudoadiabatic lifter does not require tracking of that state (at least in the same way). 
https://github.com/keltonhalbert/SHARPlib/blob/709a7015e18708134d457d4f3af1894f45b77a0f/src/SHARPlib/thermo.cpp#L285-L291
```float& rv_total, float& rv, float& rl, float& ri,``` are input-output parameters that get set, and that state belongs to ```sharp::lifter_cm1```. You can see that on every call to ```sharp::moist_adiabat_cm1```, ```rv_total``` gets set using the input pressure and temperature, which is expected to either be the LPL (lifted parcel level) or LCL. In the old method, when lifting from the LCL every time, the budget is respected because the appropriate state variable is set. 

This optimization doesn't converge because it doesn't have a correct/physical value for rv_total to use, at least in the adiabatic lifter. The pseudoadiabatic lifter does the following with said state: 
```
        if ((ma_type == adiabat::pseudo_liq) ||
            (ma_type == adiabat::pseudo_ice)) {
            rv_total = pcl_rv_hi;
            pcl_rl_hi = 0.0f;
            pcl_ri_hi = 0.0f;
        }
```
I haven't tested this branch, but I think this means the pseudoadiabatic solver should converge, since it's only dependent on the saturation mixing ratio of the new level it was lifted to, rather than the saturation mixing ratio of the LCL. 

So... In order to have this optimization work, where we don't lift from the LCL every time... we need a different way of setting, handling, and invalidating the water vapor, liquid, and ice budget state for the adiabatic solver. With my memory sufficiently jogged, this is where I got stuck last time because I couldn't find a "clean" way to do this at the time. Perhaps there is no clean way of doing it and it should just be brute-forced.

**Comment by tsupinie** [comment]
I've gotten the CM1 lifter working again. In addition to setting `rv_total` in the initialization function, I also set `rv`, `rl`, and `ri` in there and adjusted the initialization of `pcl_rv_hi`, etc. in `moist_adiabat_cm1()` accordingly. Here is the output from the tests:

| Lifter                      | EL Pres (Old) | EL Pres (New) | CAPE (Old) | CAPE (New) |
|-----------------------------|---------------|---------------|------------|------------|
| Wobus                       | 17238.2       | 17238.2       | 4124.46    | 4124.46    |
| CM1 (Pseudoadiabatic w\ice) | 17409.4       | 17409.4       | 4045.57    | 4040.98    |
| CM1 (Pseudoadiabatic)       | 17590.9       | 17590.9       | 3877.22    | 3874.71    |
| CM1 (Adiabatic w\ice)       | 16842.3       | 16842.3       | 3695.01    | 3695.14    |
| CM1 (Adiabatic)             | 17669.3       | 17669.3       | 3106.26    | 3105.91    |

Interestingly, the new EL pressures are within 0.1 Pa of the old ones, but that consistency isn't reflected in CAPE. Not sure what to make of that.

Also, that test 5 that tests the parcel lifting now takes ~0.25 s like all the other tests, whereas it used to take about 1.2 s, IIRC. I'd need to figure out the benchmarking stuff to give a better answer of how much it speeds up.

One thing we might want to consider is making `rv_total`, `rv`, `rl`, and `ri` private in the CM1 lifter. I've reset them to missing at the end of `Parcel::lift_parcel()` for safety. If we're gonna do that, we may as well make them private because they can't be used by anyone outside the lifter, anyway. But that's your call.

**Comment by keltonhalbert** [comment]
Sweet! 

The more I've thought about it, the more I agree that we should make those variables private. Much of the Parcel API has already migrated from procedural to object-based, and this change feels like it's congruent with that shift in direction. 

I'll work on making some structural changes within this PR branch and set up a benchmark. I'm generally unbothered by the minute CAPE differences, but I'll set up some new unit tests for the Parcels API (been needing to do that anyway) to increase coverage to LFC and EL pressures, as well as max and min buoyancy. Once those things are set up and tested, I'll merge into the develop branch!

**Comment by keltonhalbert** [comment]
I've decided to go ahead and merge this without the benchmark or new unit tests, since 1) it's clearly faster, with only a minor numerical difference, and 2) my attempts to do so revealed some broader changes I'd like to make outside the scope of this PR. Since it's being merged into the develop branch, this should be okay. I also wanted to merge this into the develop branch so that I can work with it in the experimental ImGui version of NSHARP!

I only made a couple of changes, primarily to make those variables private. I also changed the name of ```start_lift``` to ```setup```. While incredibly nit-picky, it made more sense to me than the idea that this routine somehow "Starts" the parcel lift.

**Pull request merged**
